color:
  brand: "#a655e4"
icon:
  menu: streamline-regular/01-interface-essential/03-menu/navigation-menu.svg
  left: streamline-regular/52-arrows-diagrams/01-arrows/arrow-left-1.svg
  right: streamline-regular/52-arrows-diagrams/01-arrows/arrow-right-1.svg
  house: streamline-regular/01-interface-essential/01-home/house-3.svg
  question: streamline-regular/01-interface essential/14-alerts/question-circle.svg
  message: streamline-regular/21-messages-chat-smileys/02-messages-speech-bubbles/messages-bubble-square-typing.svg
  info: streamline-regular/01-interface-essential/14-alerts/information-circle.svg
  invoice: streamline-regular/08-money-payments-finance/01-accounting-billing/accounting-invoice.svg
  logout: streamline-regular/01-interface-essential/04-login-logout/logout.svg
  heart_hands: streamline-regular/39-romance/01-love/love-heart-hands-hold.svg
  refresh: streamline-regular/51-real-estate/12-update/real-estate-update-house-refresh.svg
button:
  menu:
    icon: streamline-regular/01-interface-essential/03-menu/navigation-menu.svg
    menu:
      - icon: streamline-regular/01-interface-essential/01-home/house-3.svg
        text: Home
        button_id: _home
      - ---
      - icon: streamline-regular/01-interface essential/14-alerts/question-circle.svg
        text: FAQ
        button_id: _help
      - icon: streamline-regular/21-messages-chat-smileys/02-messages-speech-bubbles/messages-bubble-square-typing.svg
        text: Contact us
        button_id: _human
      - icon: streamline-regular/01-interface-essential/14-alerts/information-circle.svg
        text: About us
        button_id: _about
  app_menu:
    icon: streamline-regular/01-interface-essential/03-menu/navigation-menu.svg
    menu:
      - icon: streamline-regular/01-interface-essential/01-home/house-3.svg
        text: Home
        button_id: _home
      - icon: streamline-regular/08-money-payments-finance/01-accounting-billing/accounting-invoice.svg
        text: Balance
        button_id: _balance
      - icon: streamline-regular/39-romance/01-love/love-heart-hands-hold.svg
        text: Refer a friend
        button_id: _refer
      - icon: streamline-regular/01-interface-essential/04-login-logout/logout.svg
        text: Log out
        button_id: _log_out
      - ---
      - icon: streamline-regular/01-interface essential/14-alerts/question-circle.svg
        text: FAQ
        button_id: _help
      - icon: streamline-regular/21-messages-chat-smileys/02-messages-speech-bubbles/messages-bubble-square-typing.svg
        text: Contact us
        button_id: _human
      - icon: streamline-regular/01-interface-essential/14-alerts/information-circle.svg
        text: About us
        button_id: _about
