triggers:
  - button_id: _home

steps:
  - mode:
  - if: (@ user.app_user_id )
    then:
      jump: app
    else:
      jump: onboarding

  - (onboarding)
  - orb_header:
  - header:
      milestones:
        - text: Intro
          current: true
        - Finances
        - Options
        - Review
    page:
      - info: |
          ## 👋 Hi, welcome to MortgageTown!

          We're here to help you on your journey toward owning and living in the home of your dreams.

          Every home is ✨ unique, and so are each of our mortgages. We'll work with you to find the perfect match.

          All of the mortgages offered by MortgageTown are...
          - Affordable
          - Flexible
          - Personalized
    submit:
    extra_buttons:
      - text: Sounds good, let's get started 👍
        action:
          flow: flow.onboarding.personal
          transfer: true
      - text: Tell me more about MortgageTown 🤔
        action:
          flow: flow.about
          transfer: true

  - (app)
  - orb_header:
      buttons:
        - (@ config.button.app_menu )
  - header:
      title: Home
    page:
      - info: |
          ## 👋 Hi, (@ user.name )

          You have no new messages.

          What would you like to do today?
    submit:
    extra_buttons:
      - icon: (@ config.icon.invoice )
        text: View balance
        action:
          flow: flow.app.balance
          transfer: true
      - icon: (@ config.icon.heart_hands )
        text: Refer a friend
        action:
          flow: flow.app.refer
          transfer: true
      - icon: (@ config.icon.refresh )
        text: Renew your mortgage
        disabled: true
      - icon: (@ config.icon.message )
        text: Contact us
        action:
          flow: flow.front.human
          transfer: true
