triggers:
  - button_id: _balance

steps:
  - header:
      title: Balance
    page:
      - info: |
          Your mortgage:

          | Mortgage             | Interest rate                         |
          | -------------------- | ------------------------------------- |
          | (@ user.option.name) | (@ "%.2f"|format(user.option.rate) )% |

          Your current balance is **$(@ "%.2f"|format((user.total_price | float) - (user.downpayment | float)) )**.

          Your next payment of **$(@ "%.2f"|format(user.option.payment) )** will be automatically withdrawn on **(@ user.next_payment )**.
      - buttons:
          - icon: (@ config.icon.house )
            text: Return home
            action:
              flow: flow.home
              transfer: true
    submit:
